=== almiraj/VelXmlGenProto/src/main/resources/velXml/xsd/items.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="item" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="type">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="attr" type="xs:string" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== almiraj/VelXmlGenProto/xml/items.xml
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/items.xsd">
  <title>ITEMS_TITLE</title>
  <item>
    <title>TYPE1_TITLE</title>
    <type attr="TYPE1_ATTR">TYPE1</type>
  </item>
  <item>
    <title>TYPE2_TITLE</title>
    <type>TYPE2</type>
  </item>
</items>
